export default {
  themeColor: "#181E26",
  name: "OxPlay",
  domainURL: "https://oreobrioche.com/dewahub",
  description: "Perfect Whitelable Solution",
  theme: "dark",
  logoType: "png",
  palette: {
    primary: "#181E26",
    "primary-light": "#29313A",
    "primary-dark": "#12181F",
    brand: "#f79236",
    "brand-dark": "#f26631",
    "brand-light": "#f79236",
    "accent-primary": "#4a61e9",
    "accent-secondary": "#c5315f",
    secondary: "#fff",
    contrast: "#d5d6d5",
    inverted: "#f0f0f0",
    "text-primary": "#fff",
    "text-brand": "#fff",
    "text-accent": "#fff",
    "text-secondary": "#000",
    "icon-gradient-end": "#676767",
    "icon-gradient-start": "#899098",
    info: "#cff4fc",
    error: "#ff4d4d",
    success: "#139C44",
    warning: "#fdd835",
  },
};
